repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: poetry-run-ruff
      name: poetry run ruff
      entry: poetry run ruff .
      language: system
      types: [python]
    - id: poetry-run-black
      name: poetry run black
      entry: poetry run black .
      language: system
      types: [python]
