[tool.poetry]
name = "proof-repair"
version = "0.1.0"
description = "Tool to automatically fix Dafny proofs"
authors = ["emugnier <emugnier@ucsd.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "0.28.1"
ruff = "^0.1.0"
pyyaml = "^6.0.1"


[tool.poetry.group.dev.dependencies]
black = "^23.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [
  ".ipynb_checkpoints",
  ".pre-commit-config.yaml",
]

[tool.black]
exclude = '''
/(
  \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
| dist
| .*ipynb_checkpoints.*
| .pre-commit-config.yaml
)/
'''
