Results_dir: ./results
#Project_path: /usr/local/home/eric/dafny_repos/libraries/src
Project_path: /usr/local/home/eric/dafny_repos/libraries/src/Collections/Sets
Dafny_args: "--use-basename-for-filename --cores:2 --verification-time-limit:300 --disable-nonlinear-arithmetic"
Stats_file: ./results/stats_pruning_libraries_test.txt
