Results_dir: ./results
Project_path: ./DafnyGym/ground_truth/Dafny-VMC
Dafny_args: "--library ./DafnyGym/ground_truth/Dafny-VMC/src/**/*.dfy --resource-limit 20000"
Stats_file: ./results/stats_pruning_dafnyVMC.txt
