Results_dir: ./results
Project_path: /usr/local/home/eric/dafny_repos/Dafny-VMC
Dafny_args: "--library /usr/local/home/eric/dafny_repos/Dafny-VMC/src/**/*.dfy --resource-limit 20000"
Stats_file: ./results/stats_pruning_dafnyVMC.txt
