Results_dir: ./results
Project_path: /exp/test_projects/libraries/src/dafny/Collections/
Dafny_args: "--use-basename-for-filename --cores:2 --verification-time-limit:300 --disable-nonlinear-arithmetic"
Stats_file: ./results/stats_pruning.txt
