Results_dir: ./results
Project_path: ./DafnyGym/ground_truth/libraries/src
Dafny_args: "--use-basename-for-filename --cores:2 --verification-time-limit:300 --disable-nonlinear-arithmetic"
Stats_file: ./results/stats_pruning_libraries.txt
