Benchmarcks:

- Name: libraries-basic
  Configs:
  - configs/main/config_repos/config_llm_libraries_placeholder.yaml
  - configs/main/config_repos/config_llm_libraries_baseline.yaml
  - configs/main/config_repos/config_llm_libraries_baselineEnhancedPrompt.yaml
  - configs/main/config_repos/config_llm_libraries_error.yaml
  - configs/main/config_repos/config_llm_libraries_errorIterate.yaml
  - configs/main/config_repos/config_llm_libraries_errorplaceholder.yaml
  Content: DafnyGym/libraries.csv

- Name: vmc-basic
  Configs:
  - configs/main/config_repos/config_llm_DafnyVMC_placeholder.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_baseline.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_error.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_errorIterate.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_baselineEnhancedPrompt.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_errorplaceholder.yaml
  Content: results/placeholder_dataset/dafnyVMC.csv

- Name: cedar-basic
  Configs:
  - configs/main/config_repos/config_llm_cedar_placeholder.yaml
  - configs/main/config_repos/config_llm_cedar_baseline.yaml
  - configs/main/config_repos/config_llm_cedar_error.yaml
  - configs/main/config_repos/config_llm_cedar_errorIterate.yaml
  - configs/main/config_repos/config_llm_cedar_baselineEnhancedPrompt.yaml
  - configs/main/config_repos/config_llm_cedar_errorplaceholder.yaml
  Content: results/placeholder_dataset/cedar.csv
