Benchmarcks:
- Name: libraries
  Content: results/testing_libraries.csv
  Configs:
  - configs/main/config_repos/config_llm_libraries_static.yaml
  - configs/main/config_repos/config_llm_libraries_placeholder.yaml
- Name: cedar
  Content: results/testing_cedar.csv
  Configs:
  - configs/main/config_repos/config_llm_cedar_placeholder.yaml
  - configs/main/config_repos/config_llm_cedar_static.yaml
- Name: DafnyVMC
  Content: results/testing_dafnyVMC.csv
  Configs:
  - configs/main/config_repos/config_llm_DafnyVMC_placeholder.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_dynamic.yaml
  - configs/main/config_repos/config_llm_DafnyVMC_static.yaml
