Results_dir: ./results_llm
Prompts:
  - Context:
    System_prompt: |
      "You are a Dafny formal method expert.
      You will be provided with a Dafny method indicated by the delimiter <method>
      that does not verify because of an error indicated in between <error> tags.
      Your task is to insert at a certain line an assertion starting with `assert` to make it verify"
    Fix_prompt: "Can you fix this proof by inserting one assertion in the method <method>?"
    Method_context: "None"
    Feedback: True
    Error_feedback: False
    Nb_tries: 10
    Prompt_name: "error"
    Type: "Provided"
    Placeholder: False

Model_parameters:
  Temperature: 1
  Model: gpt-4o
  Max_tokens: 2048
  Prompt_limit: 8192
  Encoding: "cl100k_base"
Dafny_args: "--verification-time-limit:300"
Results_file: ./results_llm/stats_llm_cedar_sample10_placeholder_4t.csv
