Results_dir: ./results_llm
Prompts:
  - Context:
      Question_prompt: "Can you fix this proof by inserting one assertion in the <assertion> placeholder?"
      Threshold: 0.3
      Training_file: ./results/training_dafnyVMC.csv
      Min_cluster_length: 2
    System_prompt: |
      "You are a Dafny formal method expert.
      You will be provided with a Dafny method indicated by the delimiter <method>
      that does not verify because of an error indicated in between <error> tagsalong
      along with its dependencies with the delimiter <dependencies>.
      Your task is to insert an assertion in the <assertion> placeholder to make it verify. Your answer must start with `assert`."
    Fix_prompt: "Can you fix this proof by inserting one assertion in the <assertion> placeholder?"
    Method_context: "None"
    Feedback: False
    Nb_tries: 1
    Error_feedback: False
    Prompt_name: "static"
    Type: "Static"
    Placeholder: True
    Multiple_locations: True

Model_parameters:
  Temperature: 1
  Model: gpt-4o
  Max_tokens: 2048
  Prompt_limit: 8192
  Encoding: "cl100k_base"
Dafny_args: "--library ./DafnyGym/ground_truth/Dafny-VMC/src/**/*.dfy --resource-limit 20000"
Results_file: ./results_llm/stats_llm_DafnyVMC_sample10_placeholder_4t.csv
